# Generated by Django 3.2.9 on 2021-11-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255, verbose_name='画像ファイルのPath')),
                ('success', models.CharField(max_length=255, verbose_name='成否')),
                ('message', models.CharField(max_length=255, verbose_name='メッセージ')),
                ('data_class', models.IntegerField(db_column='class', verbose_name='クラス')),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='信頼度')),
                ('request_timestamp', models.IntegerField(verbose_name='リクエストタイムスタンプ')),
                ('response_timestamp', models.IntegerField(verbose_name='レスポンスタイムスタンプ')),
            ],
            options={
                'db_table': 'ai_analysis_log',
            },
        ),
    ]
